version: 2.1

parameters:
  tf_dir:
    type: string
    default: "terraform/"
  tf_plan:
    type: string
    default: "terraform.tfplan"
  tf_image:
    type: string
    default: "hashicorp/terraform:light"

workflows:
  pipeline:
    jobs:
      - terraform-validate
      - terraform-lint
      - terraform-plan:
          requires:
            - terraform-validate
            - terraform-lint
      - deplyoment-approval:
          type: approval
          requires:
            - terraform-plan
          filters:
            branches:
              only:
                - master
                - develop
      - terraform-apply:
          requires:
            - deplyoment-approval
          filters:
            branches:
              only:
                - master
                - develop
      - image-upload:
          requires:
            - terraform-apply
          filters:
            branches:
              only:
                - master
                - develop
      - teardown-approval:
          type: approval
          requires:
            - image-upload
          filters:
            branches:
              only:
                - master
                - develop
      - terraform-destroy:
          requires:
            - teardown-approval
          filters:
            branches:
              only:
                - master
                - develop

jobs:

  terraform-validate:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform validate << pipeline.parameters.tf_dir >>

  terraform-lint:
    docker:
      - image: wata727/tflint
    steps:
      - checkout
      - run: tflint << pipeline.parameters.tf_dir >>

  terraform-plan:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform plan -out << pipeline.parameters.tf_plan >> << pipeline.parameters.tf_dir >>
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.tf_plan >>

  terraform-apply:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform apply -auto-approve << pipeline.parameters.tf_plan >>
      - run: cd << pipeline.parameters.tf_dir >>; terraform init; terraform output ecr_url >> ./ecr_url.txt
      - persist_to_workspace:
          root: .
          paths:
            - ./ecr_url.txt

  image-upload:
    docker:
      - image: docker:19.03.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: docker build . --tag $(cat ./ecr_url.txt)
      - run: docker push $(cat ./ecr_url.txt)

  terraform-destroy:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform destroy -auto-approve << pipeline.parameters.tf_dir >>
