# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  tf_dir:
    type: string
    default: "${CIRCLE_WORKING_DIRECTORY}/terraform/"
  ci_scripts_dir:
    type: string
    default: "${CIRCLE_WORKING_DIRECTORY}/ci_scripts/"

workflows:
  pipeline:
    jobs:
      - terraform-validate
      - terraform-plan

jobs:

  terraform-validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: pwd
      - run: sh << pipeline.parameters.ci_scripts_dir >>tf_validate.sh << pipeline.parameters.tf_dir >>

  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: sh << pipeline.parameters.ci_scripts_dir >>tf_plan.sh << pipeline.parameters.tf_dir >>

  # terraform-apply:
  #   branches:
  #     only:
  #       - master
  #       - develop
  #   steps:
  #     - checkout
  #     - run: terraform -v
  #     - run: terraform init terraform/
  #     - run: terraform plan terraform/ -var="build=${CIRCLE_BRANCH}"
