# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  tf_dir:
    type: string
    default: "terraform/"
  tf_plan:
    type: string
    default: "tf.plan"
  tf_image:
    type: string
    default: "hashicorp/terraform:light"

workflows:
  pipeline:
    jobs:
      - terraform-validate
      - terraform-lint
      - terraform-plan:
          requires:
            - terraform-validate
            - terraform-lint
      - terraform-apply-approval:
          type: approval
          requires:
            - terraform-plan
          filters:
            branches:
              only:
                - master
                - develop
      - terraform-apply:
          requires:
            - terraform-apply-approval
          filters:
            branches:
              only:
                - master
                - develop
      - terraform-destroy-approval:
          type: approval
          requires:
            - terraform-apply
          filters:
            branches:
              only:
                - master
                - develop
      - terraform-destroy:
          requires:
            - terraform-destroy-approval
          filters:
            branches:
              only:
                - master
                - develop

jobs:

  terraform-validate:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform validate << pipeline.parameters.tf_dir >>

  terraform-lint:
    docker:
      - image: wata727/tflint
    steps:
      - checkout
      - run: tflint << pipeline.parameters.tf_dir >>

  terraform-plan:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform plan -out << pipeline.parameters.tf_plan >> << pipeline.parameters.tf_dir >>
      - run: cat << pipeline.parameters.tf_plan >>
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.tf_plan >>

  terraform-apply:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: terraform apply << pipeline.parameters.tf_plan >> -auto-approve

  terraform-destroy:
    docker:
      - image: << pipeline.parameters.tf_image >>
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      # - run: terraform destroy << pipeline.parameters.tf_dir >> -var="env=${CIRCLE_BRANCH}" -auto-approve
