# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  tf_dir:
    type: string
    default: "terraform/"

workflows:
  pipeline:
    jobs:
      - terraform-validate
      - terraform-lint
      - terraform-plan:
          requires:
            - terraform-validate
            - terraform-lint
      - check-plan:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - check-plan

jobs:

  terraform-validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform validate << pipeline.parameters.tf_dir >>

  terraform-lint:
    docker:
      - image: wata727/tflint
    steps:
      - checkout
      - run: tflint << pipeline.parameters.tf_dir >>

  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init << pipeline.parameters.tf_dir >>
      - run: terraform plan << pipeline.parameters.tf_dir >>

  check-plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: echo "Check plan !"

  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    branches:
      only:
        - master
        - develop
    steps:
      - checkout
      - run: terraform init terraform/
      - run: terraform plan terraform/ -var="build=${CIRCLE_BRANCH}"
